const PlayErrorCode = {
  // 位置错误类型
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  // 路由错误
  ROUTER_ERROR: 'ROUTER_ERROR',
  // 打开大厅会话错误
  OPEN_LOBBY_SESSION_ERROR: 'OPEN_LOBBY_SESSION_ERROR',
  // 打开游戏会话错误
  OPEN_GAME_SESSION_ERROR: 'OPEN_GAME_SESSION_ERROR',
  // 加入大厅服务错误
  JOIN_LOBBY_ERROR: 'JOIN_LOBBY_ERROR',
  // 大厅创建房间错误
  LOBBY_CREATE_ROOM_ERROR: 'LOBBY_CREATE_ROOM_ERROR',
  // 连接游戏服务器错误
  CONNECT_GAME_SERVER_ERROR: 'CONNECT_GAME_SERVER_ERROR',
  // 游戏创建房间错误
  GAME_CREATE_ROOM_ERROR: 'GAME_CREATE_ROOM_ERROR',
  // 大厅加入房间错误
  LOBBY_JOIN_ROOM_ERROR: 'LOBBY_JOIN_ROOM_ERROR',
  // 游戏加入房间错误
  GAME_JOIN_ROOM_ERROR: 'GAME_JOIN_ROOM_ERROR',
  // 大厅随机加入房间错误
  LOBBY_JOIN_RANDOM_ROOM_ERROR: 'LOBBY_JOIN_RANDOM_ROOM_ERROR',
  // 打开 WebSocket 错误
  OPEN_WEBSOCKET_ERROR: 'OPEN_WEBSOCKET_ERROR',
  // 关闭 WebSocket 错误
  CLOSE_WEBSOCKET_ERROR: 'CLOSE_WEBSOCKET_ERROR',
  // 发送消息状态错误
  SEND_MESSAGE_STATE_ERROR: 'SEND_MESSAGE_STATE_ERROR',
};

export default PlayErrorCode;
